# Generated by Django 6.0.3 on 2026-04-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('product_des', models.TextField()),
                ('product_prize', models.CharField(max_length=50)),
            ],
        ),
    ]
