# Generated by Django 6.0.3 on 2026-04-20 07:07

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_des',
            field=tinymce.models.HTMLField(),
        ),
    ]
